# Generated by Django 4.0 on 2022-01-24 14:15

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AUD', 'Audio'), ('IMG', 'Image')], max_length=3)),
                ('document_file', models.FileField(upload_to=index.models.Document.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('TRD', 'Thread'), ('NWS', 'News')], max_length=3)),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.content')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', models.TextField()),
                ('question_answers', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('INP', 'Input'), ('TOF', 'True False'), ('OIM', 'One Choice')], max_length=3)),
                ('question_documents', models.ManyToManyField(blank=True, to='index.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.profile'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_title', models.CharField(max_length=255)),
                ('exercise_statement', models.TextField()),
                ('exercise_options', models.CharField(blank=True, max_length=255)),
                ('exercise_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('exercise_documents', models.ManyToManyField(blank=True, to='index.Document')),
                ('exercise_questions', models.ManyToManyField(to='index.Question')),
            ],
        ),
    ]
