# Generated by Django 4.0 on 2022-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_language',
            field=models.CharField(choices=[('AL', 'All'), ('EN', 'English'), ('DE', 'German'), ('FR', 'French')], default='AL', max_length=2),
        ),
    ]
