# Generated by Django 4.0 on 2022-01-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_news_news_state_thread_thread_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_state',
            new_name='post_state',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_state',
        ),
        migrations.AddField(
            model_name='news',
            name='post_state',
            field=models.CharField(choices=[('Yet to happen', 'Will Happen'), ('Happening today', 'Happening'), ('Already happened', 'Happened')], default='Yet to happen', max_length=24),
        ),
    ]
