# Generated by Django 4.0 on 2022-01-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_thread_state_thread_post_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_language',
            field=models.CharField(choices=[('ALL', 'All'), ('EN', 'English'), ('DE', 'German'), ('FR', 'French')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Thread', 'Thread'), ('News', 'News')], max_length=8),
        ),
        migrations.AlterField(
            model_name='thread',
            name='post_state',
            field=models.CharField(choices=[('Open', 'Not Answered'), ('Answered', 'Answered')], default='Open', max_length=12),
        ),
    ]
