# Generated by Django 4.0 on 2022-01-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_news_news_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative')], max_length=3)),
                ('reaction_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
                ('reaction_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.profile')),
            ],
            options={
                'unique_together': {('reaction_profile', 'reaction_post')},
            },
        ),
    ]
