# Generated by Django 4.0 on 2022-01-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateField(auto_now_add=True)),
                ('reply_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.content')),
                ('reply_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.profile')),
            ],
        ),
    ]
