# Generated by Django 4.0 on 2022-01-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_reply_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_old',
            field=models.BooleanField(default=False),
        ),
    ]
