# Generated by Django 4.0 on 2022-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_news_news_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.CharField(choices=[('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_0.png', 'Avatar 0'), ('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_1.png', 'Avatar 1'), ('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_2.png', 'Avatar 2'), ('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_3.png', 'Avatar 3'), ('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_4.png', 'Avatar 4'), ('/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_5.png', 'Avatar 5')], default='/Users/telos_matter/Documents/django_workspace/amets04/index/static/index/images/avatar_0.png', max_length=255),
        ),
    ]
