# Generated by Django 4.0 on 2022-01-28 17:03

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_profile_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=255)),
                ('resource_file', models.FileField(upload_to=index.models.Resource.upload_to)),
                ('resource_type', models.CharField(choices=[('History', 'H'), ('Technology', 'T'), ('Science', 'S'), ('Novel', 'N'), ('Article', 'A')], max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.CharField(choices=[('index/images/avatars/avatar_0.png', 'Avatar 0'), ('index/images/avatars/avatar_1.png', 'Avatar 1'), ('index/images/avatars/avatar_2.png', 'Avatar 2'), ('index/images/avatars/avatar_3.png', 'Avatar 3'), ('index/images/avatars/avatar_4.png', 'Avatar 4'), ('index/images/avatars/avatar_5.png', 'Avatar 5')], default='index/images/avatars/avatar_0.png', max_length=255),
        ),
    ]
